### ISSUE TITLE
Видится только один датчик под номером 8 .

### ISSUE THREAD

**Issue by enigmaspb** [volshebniks/sauresha#10]
В контроллере использовано 6 датчиков 
1-2 счетчики воды
3-4 - пустые 
5 - контакт закрытия гидролока
6 - датчик наличия 220в
7- Датчик тембературы
8- контакт аларма гидролока

Расширение настроено так 
##############################
sensor:
  - platform: sauresha
    email: !secret saures_login
    password: !secret saures_password
    flat_id: XXXX
    scan_interval:
      minutes: 60
    counters_sn:
      - 000001
      - 000002
      - 000007
    controllers_sn:
      - 84XXXXXXXXXX

##############################

binary_sensor:
  - platform: sauresha
    email: !secret saures_login
    password: !secret saures_password
    flat_id: XXXX
    counters_sn:
      - 000005
      - 000006
      - 000008
##############################

В Home assistant видится и получает данные только датчик под номером 8 и сам контроллер и его статус 
все остальные не видятся и не получают данные , в логе пусто . 

https://a.radikal.ru/a20/2102/68/da584049425b.png

подскажите где ошибка и куда смотреть ?

**Comment by volshebniks** [comment]
проверить, что кол-во пробелов в настройках правильно.
настройки должны выглядеть так:
```
- platform: sauresha
  email:  vols@gmail.com
  password: aE99UA3cVVVVVV
 controllers_sn:
    - 84F3XXXXXXXX
  counters_sn:
    - 12311111
    - 12311112
  scan_interval:
    minutes: 15
```


попробовать добавлять датчики по одному.
