### ISSUE TITLE
не получается сконфигурировать сенсоры и бинарные сенсоры одновременно

### ISSUE THREAD

**Issue by V-A-S** [volshebniks/sauresha#15]
сам компонент сконфигурирован, в интерфейсе ХА видна информация о контроллере, счетчиках, но как только создается файл конфигурации (и перезапускается ХА) бинарных сенсоров (датчики протечки), то становятся нормально видны только они, со своими статусами, а ранее сконфигурированные сенсоры переходят в "Unknown". файл конфига бинарных сенсоров удаляю, перезапускаю ХА, все опять в порядке: контроллер и счетчики отображаются, как положено
sensors.yaml
```
- platform: sauresha
  email: !secret saures_uid
  password: !secret saures_pwd
  flat_id: !secret saures_flt
  scan_interval:
          minutes: 60
  controllers:
          FAFAFAFAFAFA:
                  name: SauresR5
  counters:
          20-123456:
                  name: hot_water_cntr
          20-654321:
                  name: cold_water_cntr
```
bin_sensors.yaml
```
- platform: sauresha
  email: !secret saures_uid
  password: !secret saures_pwd
  flat_id: !secret saures_flt
  counters:
          211111:
                  name: ""
          222222:
                  name: ""
          233333:
                  name: ""
```
