### ISSUE TITLE
Недоступны данные saures meters сконфигурированных как binary sensor 

### ISSUE THREAD

**Issue by Gimlir** [volshebniks/sauresha#19]
К контроллеру Saures R2 4.0 (прошивка 4.4.3) подключено 2 счетчика, 3 датчика протечки и 2 крана гидролока (на 3 прота - 2 порта на состояние каждого из кранов и 1 порт на управление обоими кранами сразу в параллель).

Данные контроллера и счетчиков получаю, но данные бинарных сенсоров - недоступно.
В HA объекты создались, но выглядят вот так 
![image](https://user-images.githubusercontent.com/39776670/147165537-a335ab37-0387-4d7d-bae4-78fcab515a08.png)

Интеграция версии 0.6.2 установлена ручным способом, HA версии 2021.12.3 в докер контейнере установлен по оф. мануалу HA

конфиг sensor
```
- platform: sauresha
  email: !secret sensor_saures_email
  password: !secret sensor_saures_password
  flat_id: !secret sensor_saures_flat_id
  controllers:
    !secret sensor_saures_controller_sn_water:
      name: Controller_Saures
  counters:
    !secret sensor_saures_counter_sn_cold:
      name: Cold_water
    !secret sensor_saures_counter_sn_hot:
      name: Hot_water
  scan_interval:
    minutes: 60
```

конфиг binary_sensor
```
- platform: sauresha
  email: !secret sensor_saures_email
  password: !secret sensor_saures_password
  flat_id: !secret sensor_saures_flat_id
  scan_interval:
    minutes: 60
  counters:
    !secret sensor_saures_leak_1:
      name: leak1
    !secret sensor_saures_leak_2:
      name: leak2
    !secret sensor_saures_leak_3:
      name: leak3
    !secret sensor_saures_valve_status_hot:
      name: hot_valve
    !secret sensor_saures_valve_status_cold:
      name: cold_valve
```
 
оба ссылаются на общий secrets
```
sensor_saures_email: "a**********e"
sensor_saures_password: "***********"
sensor_saures_flat_id: *****3
sensor_saures_controller_sn_water: ******08
sensor_saures_counter_sn_hot: ******81
sensor_saures_counter_sn_cold: ******92
sensor_saures_leak_1: ***88
sensor_saures_leak_2: ***89
sensor_saures_leak_3: ***90
sensor_saures_valve_status_hot: ***92
sensor_saures_valve_status_cold: ***93
```
в логе HA нет никаких сообщений

если перехватить ответы API в родном ЛК Saures, то информация по датчикам протечки и кранам там отдается в таком виде:
запрос вида
`https://api.saures.ru/1.0/object/meters?sid=***********&id=*****3&date=2021-12-23T23:59:59` 
ответ
```
{
	"data": {
		"sensors": [
			{
				"sn": "******08",
				"name": "",
				"active": true,
				"ssid": "Wi-Fi: *********",
				"hardware": "4.0",
				"firmware": "4.4.3",
				"new_firmware": "",
				"bat": 50,
				"local_ip": "192.168.******",
				"check_hours": 48,
				"check_period_display": "1 час",
				"last_connection": "2021-12-23T01:31:32",
				"last_connection_warning": null,
				"lic_channels": null,
				"requests": 11272,
				"rssi": "-60",
				"log": 60,
				"scan": 5,
				"vol": 200,
				"readout_dt": "2021-12-23T01:00:00",
				"request_dt": "2021-12-23T01:31:32",
				"cap_state": false,
				"power_supply": false,
				"nbiot": false,
				"meters": [
					{
						"meter_id": ***86,
						"meter_name": "Счетчик Горячая",
						"input": 1,
						"approve_dt": "2025-07-12",
						"eirc_num": "*****81",
						"sn": "******81",
						"type": {
							"name": "Горячая вода",
							"number": 2
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "м³",
						"vals": [
							122.161
						]
					},
					{
						"meter_id": ****87,
						"meter_name": "Счетчик Холодная",
						"input": 2,
						"approve_dt": "2025-07-12",
						"eirc_num": "*****92",
						"sn": "******92",
						"type": {
							"name": "Холодная вода",
							"number": 1
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "м³",
						"vals": [
							266.803
						]
					},
					{
						"meter_id": *****88,
						"meter_name": "Протечка Ванная",
						"input": 3,
						"approve_dt": null,
						"eirc_num": "",
						"sn": "",
						"type": {
							"name": "Датчик",
							"number": 9
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "",
						"vals": [
							0
						],
						"active_text": "Активен",
						"passive_text": "Неактивен"
					},
					{
						"meter_id": *****89,
						"meter_name": "Протечка Кухня",
						"input": 4,
						"approve_dt": null,
						"eirc_num": "",
						"sn": "",
						"type": {
							"name": "Датчик",
							"number": 9
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "",
						"vals": [
							0
						],
						"active_text": "Активен",
						"passive_text": "Неактивен"
					},
					{
						"meter_id": *****90,
						"meter_name": "Протечка сантехшкаф",
						"input": 5,
						"approve_dt": null,
						"eirc_num": "",
						"sn": "",
						"type": {
							"name": "Датчик",
							"number": 9
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "",
						"vals": [
							0
						],
						"active_text": "Активен",
						"passive_text": "Неактивен"
					},
					{
						"meter_id": *****91,
						"meter_name": "Краны управление",
						"input": 6,
						"approve_dt": null,
						"eirc_num": "",
						"sn": "",
						"type": {
							"name": "Кран/реле",
							"number": 6
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "",
						"vals": [
							0
						],
						"active_text": "Закрытие",
						"passive_text": "Открытие"
					},
					{
						"meter_id": ******92,
						"meter_name": "Кран Горячая",
						"input": 7,
						"approve_dt": null,
						"eirc_num": "",
						"sn": "",
						"type": {
							"name": "Состояние крана",
							"number": 10
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "",
						"vals": [
							0
						],
						"active_text": "Закрыт",
						"passive_text": "Открыт"
					},
					{
						"meter_id": *****93,
						"meter_name": "Кран Холодная",
						"input": 8,
						"approve_dt": null,
						"eirc_num": "",
						"sn": "",
						"type": {
							"name": "Состояние крана",
							"number": 10
						},
						"state": {
							"name": "Ошибок нет",
							"number": 0
						},
						"unit": "",
						"vals": [
							0
						],
						"active_text": "Закрыт",
						"passive_text": "Открыт"
					}
				]
			}
		]
	}
}
```
окончания идентификаторов для удобства сравнения с конфигом оставил

Буду признателен за подсказку, в какую сторону копать?
