### ISSUE TITLE
некорректные показания электросчетчика

### ISSUE THREAD

**Issue by no157ru** [volshebniks/sauresha#58]
HA: последняя (2024.2.01)
SauresHA: последняя
Контроллер R4 (hw 4.1, fw 4.4.5)
Электросчетчик: Меркурий 230 (три фазы, два тарифа день/ночь)

Суть проблемы:
На закладке "Энергия" добавил электросчетчик в качестве источника информации о потреблении электричества из сети. Показаний нет. Истории нет. В настройках этого раздела HA пишет об ошибке: 

У объекта нечисловое состояние
Следующие объекты имеют состояния, которые не распознаются как число:
sensor.saures_merkurii_230 (55091.662/23770.541)

При этом на пользовательской вкладке добавил две карточки для атрибутов T1 и T2 этого же счетчика. И с ними все хорошо - и ошибок нет, и графики рисует.

Причина в том, что с объекта "сенсор" приезжает два значения с точкой в качестве разделителя целой и дробной части, а в атрибутах - как положено, через запятую. Наверное, правильно было-бы привести сложить значения атрибутов Т1, Т2, Т3 и Т4 и в качестве значения сенсора выдавать итоговую сумму с корректным разделителем целой и дробной частей, либо округленное до ближайшего целого.

**Comment by oneevil** [comment]
```
sensor:
  - platform: template
    sensors:
      enegry_t1:
        friendly_name: "Электричество T1"
        icon_template: mdi:counter
        unit_of_measurement: kWh
        device_class: energy
        value_template: "{{ (states('sensor.saures_elektroenergiia').split('/')[0] | float) }}"
      enegry_t2:
        friendly_name: "Электричество T2"
        icon_template: mdi:counter
        unit_of_measurement: kWh
        device_class: energy
        value_template: "{{ (states('sensor.saures_elektroenergiia').split('/')[1] | float) }}"

template:
  - sensor:
      - name: "Общий расход электричества"
        state: "{{ (states('sensor.saures_elektroenergiia').split('/')[0] | float) + (states('sensor.saures_elektroenergiia').split('/')[1] | float) }}"
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
```
