### ISSUE TITLE
Разные показания счетчиков в HA и ЛК Сауреса

### ISSUE THREAD

**Issue by avbor** [volshebniks/sauresha#6]
Привет,  только что заметил расхождение в данных полученых с ХА с тем, что есть в ЛК.
В ХА у меня сейчас так:
![image](https://user-images.githubusercontent.com/32452033/98522041-43e4e080-2285-11eb-8d64-3d7d857df54c.png)
Счетчик обновлен недавно:
![image](https://user-images.githubusercontent.com/32452033/98522148-65de6300-2285-11eb-940d-0e7f459cfed8.png)

А в ЛК:
![image](https://user-images.githubusercontent.com/32452033/98522189-7262bb80-2285-11eb-9985-bf950cf14587.png)

В чем может быть проблема?

**Comment by avbor** [comment]
Данные обновились, но с какой то дикой задержкой в несколько дней:
![image](https://user-images.githubusercontent.com/32452033/98693116-f057bd00-2380-11eb-8132-b3eca6a42056.png)

...но расхождение есть и сейчас, в ЛК значение больше чем в ХА...

**Comment by volshebniks** [comment]
Есть одна идея, как принудительно не использовать кеш на стороне Saures.
Как будет время проверю.

**Comment by avbor** [comment]
Т.е. это кэш на их стороне? Класс.
Чет ребята совсем куда-то не в ту сторону со своим апи идут...

**Comment by volshebniks** [comment]
выложите пожалуйста настройки  всех сенсоров (обычных и бинарных)

**Comment by avbor** [comment]
Бинарный сенсор убрал давно, ссмысла в нем больше нет.
Обычный:
```
- platform: sauresha
  email: !secret saures_user
  password: !secret saures_pass
  flat_id: !secret saures_flat_id
  scan_interval:
    minutes: 90
  counters_sn: 
      - sn
      - sn
  controllers_sn: 
      - sn
```
